"""
Leads iniciales del proveedor (VORTEX S.L.).

Son los negocios que el fundador ya tenía trabajados en la app de captación
(04-captacion-clientes/app.js, constante INITIAL_LEADS), que los guardaba en el
localStorage del navegador. Aquí quedan como semilla: el servidor los importa
UNA sola vez al arrancar con la tabla de leads recién creada (ver db._seed_leads)
y a partir de ese momento la verdad está en la base de datos, no en este fichero.

Conversión aplicada respecto al fichero original:
  name  -> business_name    type   -> business_type
  angle -> se une a notes (el ángulo comercial es información valiosa)
  todos entran en la línea "pos" y estado "nuevo", que es donde estaban.
"""

SEED_LEADS = [
    {
        "id": "cafe-bar-ocana-amarilla",
        "business_name": "Cafe-Bar Ocana Amarilla",
        "contact": "",
        "phone": "+34 640 53 18 56",
        "email": "",
        "zone": "Velez-Malaga",
        "business_type": "Cafe-bar / comida preparada",
        "line": "pos",
        "status": "nuevo",
        "priority": "alta",
        "source": "captación inicial",
        "notes": "Ángulo: negocio familiar, contacto por WhatsApp y perfil ideal para TPV sencillo · Primer lead con telefono publico. Ideal para validar el mensaje.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "taberna-restaurante-padre-pio",
        "business_name": "Taberna Restaurante Padre Pio",
        "contact": "",
        "phone": "",
        "email": "info@restaurantepadrepio.es",
        "zone": "Torre del Mar",
        "business_type": "Taberna restaurante",
        "line": "pos",
        "status": "nuevo",
        "priority": "alta",
        "source": "captación inicial",
        "notes": "Ángulo: taberna tradicional con email publico y posible mejora de gestion de comandas · Lead caliente por email.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "bar-la-cueva-freiduria",
        "business_name": "Bar La Cueva Freiduria y Marisco",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Torre del Mar",
        "business_type": "Bar de tapas / freiduria",
        "line": "pos",
        "status": "nuevo",
        "priority": "alta",
        "source": "captación inicial",
        "notes": "Ángulo: freiduria tradicional, probable sistema manual o TPV antiguo · Requiere visita o busqueda de contacto.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "jordi-bar-tapas",
        "business_name": "Jordi Bar Tapas",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Torre del Mar",
        "business_type": "Bar de tapas",
        "line": "pos",
        "status": "nuevo",
        "priority": "alta",
        "source": "captación inicial",
        "notes": "Ángulo: bar de tapas con alto encaje para comandas rapidas · Requiere visita o busqueda de contacto.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "cafeteria-badara",
        "business_name": "Cafeteria Badara",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Caleta de Velez",
        "business_type": "Cafeteria",
        "line": "pos",
        "status": "nuevo",
        "priority": "alta",
        "source": "captación inicial",
        "notes": "Ángulo: cafeteria pequena con operativa repetitiva y tickets rapidos · Requiere visita o busqueda de contacto.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "chiringuito-la-isla-playa",
        "business_name": "Chiringuito La Isla Playa",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Torre del Mar",
        "business_type": "Chiringuito",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: negocio estacional, encaja con suscripcion pausable por temporada · Tiene web publica. Buscar email o WhatsApp antes de contactar.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "el-saladero",
        "business_name": "El Saladero",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Caleta de Velez",
        "business_type": "Chiringuito / restaurante",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: alto volumen y visibilidad, potencial caso de exito · Objetivo premium. Mejor visita en horario tranquilo.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "chinchin-puerto",
        "business_name": "Chinchin Puerto",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Caleta de Velez",
        "business_type": "Chiringuito / restaurante",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: alto volumen, visibilidad local y plan profesional · Objetivo premium. Mejor visita en horario tranquilo.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "cafe-bar-geminis",
        "business_name": "Cafe-Bar Geminis",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Velez-Malaga",
        "business_type": "Bar de tapas",
        "line": "pos",
        "status": "nuevo",
        "priority": "alta",
        "source": "captación inicial",
        "notes": "Ángulo: negocio de tapas familiar con especialidades y flujo de comandas · Requiere visita o busqueda de contacto.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "helados-ana-garrigos",
        "business_name": "Helados Ana Garrigos",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Velez-Malaga / Torre del Mar",
        "business_type": "Heladeria artesanal",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: tres locales, temporada alta y posible multi-ubicacion · Buscar contacto por Facebook o visita.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "sicilia-gelati",
        "business_name": "Sicilia Gelati",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Torre del Mar",
        "business_type": "Heladeria artesanal",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: ticket rapido, colas en temporada y necesidad de cobro agil · Requiere visita o busqueda de contacto.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "marisqueria-el-radar",
        "business_name": "Marisqueria El Radar",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Torre del Mar",
        "business_type": "Marisqueria",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: alto volumen, posible interes por informes y control de caja · Puede tener TPV; enfocar en facilidad, precio y sin permanencia.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "menade-restaurant",
        "business_name": "Menade Restaurant",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Caleta de Velez",
        "business_type": "Restaurante",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: restaurante bien valorado, posible encaje por gestion y reporting · Puede tener TPV; enfocar en demo comparativa.",
        "next_action": "",
        "next_date": "",
    },
    {
        "id": "hostal-cafeteria-la-estacion",
        "business_name": "Hostal Cafeteria La Estacion",
        "contact": "",
        "phone": "",
        "email": "",
        "zone": "Benajarafe",
        "business_type": "Hostal + cafeteria + heladeria",
        "line": "pos",
        "status": "nuevo",
        "priority": "media",
        "source": "captación inicial",
        "notes": "Ángulo: tres lineas de negocio en una, buena oportunidad de plan crecimiento · Requiere visita o busqueda de contacto.",
        "next_action": "",
        "next_date": "",
    },
]
